[workspace]
resolver = "2"
members = ["core", "gui", "voice"]


[workspace.dependencies]
anyhow = { version = "1.0.95" }
tokio = { version = "1.43.0", features = ["full"] }
crossbeam-channel = { version = "0.5.14" }
eframe = { version = "0.31.0" }
