[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.8.0"

spin = "0.9.8"


[build-dependencies]
toml = "0.8.20"
rustc-cfg = "0.5.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
