[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
eframe = { workspace = true }
anyhow = { workspace = true }
voice = { path = "../voice" }
cpal = { version = "0.15.3" }
gui = { path = "../gui" }
