[package]
name = "voice"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
cpal = "0.15.3"
tokio = { workspace = true }
anyhow = { workspace = true }
crossbeam-channel = { workspace = true }
ndarray = "0.16.1"
rustfft = "6.2.0"
